config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  #get 'sessions/new'
  #post 'sessions/new'
  #get 'sessions/create'
  #get 'sessions/destroy'
  resources :sessions
  resources :articles
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'welcome/index'

  root 'welcome#index'

  #get 'admin' => 'admin#index'
#
  #controller :sessions do
  #  get 'login' => :new
  #  post 'login' => :create
  #  delete 'logout' => :destroy
  #end

end

app/views/partials/_navBar.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= yield(:title) %></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<style>

html { width: 100%; height:100%; overflow:hidden; }

.navbar-inverse{
  border: 0px;
  background-color:rgba(34, 34, 34, 0.5);
}

body {
	width: 100%;
	height:100%;
	font-family: 'Open Sans', sans-serif;
	background: #092756;
	background: -moz-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%),-moz-linear-gradient(top,  rgba(57,173,219,.25) 0%, rgba(42,60,87,.4) 100%), -moz-linear-gradient(-45deg,  #670d10 0%, #092756 100%);
	background: -webkit-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -webkit-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -webkit-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
	background: -o-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -o-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -o-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
	background: -ms-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -ms-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -ms-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
	background: -webkit-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), linear-gradient(to bottom,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), linear-gradient(135deg,  #670d10 0%,#092756 100%);
	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#3E1D6D', endColorstr='#092756',GradientType=1 );
}
</style>
<body>

<nav class="navbar navbar-inverse" style="border-radius: 0px;">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to (raw('<span class="navbar-brand"><b style="font-size:30px">🌈 Secret Diary 🦄</b></span>')), "/welcome/index", class: "link" %>
    </div>
    <ul class="nav navbar-nav">

      <% if current_user %>
        <li style="font-size:20px"><%= link_to "🤫 Posts 🤫", "/articles/", class: "link" %></li>
        <li style="font-size:20px"><%= link_to "📝 Create post 📝", "/articles/new", class: "link" %></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">

      <% if current_user %>

      <li style="font-size:20px"><%= link_to (raw('<span class="glyphicon glyphicon-log-out"></span> Log Out')), session_path("current"), method: "delete", class: "link" %></a></li>

      <% else %>

      <li style="font-size:20px"><%= link_to (raw('<span class="glyphicon glyphicon-user"></span> Sign up')), new_user_path, class: "link" %></a></li>
      <li style="font-size:20px"><%= link_to (raw('<span class="glyphicon glyphicon-log-in"></span> Log in')), new_session_path, class: "link" %></a></li>

      <% end %>
    </ul>
  </div>
</nav>

app/views/partials/_session.html.erb

<!-- no ha iniciado sesion-->
<% if !current_user %>
  <% redirect_to '/sessions/new', notice: "Please log in" %>
<% end %>